spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todos
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt.signing.key.secret: mySecret
jwt.get.token.uri: /authenticate
jwt.refresh.token.uri: /refresh
jwt.http.request.header: Authorization
jwt.token.expiration.in.seconds: 604800